const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    GOOGLE_SIGN_IN_SUCCESS: 'GOOGLE_SIGN_IN_SUCCESS',
    GOOGLE_SIGN_IN_FAILURE: 'GOOGLE_SIGN_IN_FAILURE',
    EMAIL_SIGN_IN: 'EMAIL_SIGN_IN',
    EMAIL_SIGN_SUCCESS: 'EMAIL_SIGN_SUCCESS',
    EMAIL_SIGN_FAILURE: 'EMAIL_SIGN_FAILURE',
};

export default UserActionTypes;